import { Artifact } from "../intefaces/artifact.interface";

export const artifactListConfig: Artifact[] = [
  { name: "Battery", source: "battery.png" },
  { name: "Broken Rock", source: "broken-rock.png" },
  { name: "Bubble", source: "bubble.png" },
  { name: "Cavity", source: "cavity.png" },
  { name: "Chocolate Bar", source: "chocolate-bar.png" },
  { name: "Cilliate", source: "cilliate.png" },
  { name: "Compass", source: "compass.png" },
  { name: "Crest", source: "crest.png" },
  { name: "Crown", source: "crown.png" },
  { name: "Crust", source: "crust.png" },
  { name: "Crystal Thorn", source: "crystal-thorn.png" },
  { name: "Crystal", source: "crystal.png" },
  { name: "Dead Sponge", source: "dead-sponge.png" },
  { name: "Devil's Mushroom", source: "devils-mushroom.png" },
  { name: "Droplets", source: "droplets.png" },
  { name: "Eye", source: "eye.png" },
  { name: "Flash", source: "flash.png" },
  { name: "Fireball", source: "fireball.png" },
  { name: "Flaw", source: "flaw.png" },
  { name: "Flower Bud", source: "flower-bud.png" },
  { name: "Flytrap", source: "flytrap.png" },
  { name: "Glare", source: "glare.png" },
  { name: "Goldfish", source: "goldfish.png" },
  { name: "Gravi", source: "gravi.png" },
  { name: "Harp", source: "harp.png" },
  { name: "Horn", source: "horn.png" },
  { name: "Hypercube", source: "hypercube.png" },
  { name: "Jellyfish", source: "jellyfish.png" },
  { name: "Kolobok", source: "kolobok.png" },
  { name: "Lantern", source: "lantern.png" },
  { name: "Liquid Rock", source: "liquid-rock.png" },
  { name: "Lyre", source: "lyre.png" },
  { name: "Magic Cube", source: "magic-cube.png" },
  { name: "Magma", source: "magma.png" },
  { name: "Mama's Beads", source: "mamas-beads.png" },
  { name: "Meat Chunk", source: "meat-chunk.png" },
  { name: "Meat Lighter", source: "meat-lighter.png" },
  { name: "Mica", source: "mica.png" },
  { name: "Mold", source: "mold.png" },
  { name: "Moonlight", source: "moonlight.png" },
  { name: "Night Star", source: "night-star.png" },
  { name: "Pebble", source: "pebble.png" },
  { name: "Pellicle", source: "pellicle.png" },
  { name: "Petal", source: "petal.png" },
  { name: "Plasma", source: "plasma.png" },
  { name: "Rat King", source: "rat-king.png" },
  { name: "Rosin", source: "rosin.png" },
  { name: "Sapphire", source: "sapphire.png" },
  { name: "Shell", source: "shell.png" },
  { name: "Shop Class", source: "shop-class.png" },
  { name: "Skipjack", source: "skipjack.png" },
  { name: "Slime", source: "slime.png" },
  { name: "Slug", source: "slug.png" },
  { name: "Snowflake", source: "snowflake.png" },
  { name: "Soul", source: "soul.png" },
  { name: "Sparkler", source: "sparkler.png" },
  { name: "Spinner", source: "spinner.png" },
  { name: "Spring", source: "spring.png" },
  { name: "Starfish", source: "starfish.png" },
  { name: "Steak", source: "steak.png" },
  { name: "Stone Blood", source: "stone-blood.png" },
  { name: "Stone Heart", source: "stone-heart.png" },
  { name: "Thorn", source: "thorn.png" },
  { name: "Thunderberry", source: "thunderberry.png" },
  { name: "Torch", source: "torch.png" },
  { name: "Tourist Breakfast", source: "tourist-breakfast.png" },
  { name: "Urchin", source: "urchin.png" },
  { name: "Whirlwind", source: "whirlwind.png" },
  { name: "Wierd Ball", source: "wierd-ball.png" },
  { name: "Wierd Bolt", source: "wierd-bolt.png" },
  { name: "Wierd Flower", source: "wierd-flower.png" },
  { name: "Wierd Nut", source: "wierd-nut.png" },
  { name: "Wierd Pot", source: "wierd-pot.png" },
  { name: "Wierd Water", source: "wierd-water.png" },
  { name: "Wrenched", source: "wrenched.png" },
];
